AWSTemplateFormatVersion: '2010-09-09'
Description: Despliegue Landing Page sobre instancia EC2 con ubuntu 20.04
Parameters:
  Region:
    Description: AWS Region
    Type: String
    Default: 'us-east-1'
  EC2AMI:
    Description: Imagen del Sistema Operativo
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/canonical/ubuntu/server/20.04/stable/current/amd64/hvm/ebs-gp2/ami-id'
  KeyName:
    Description: Par clave valor para acceso SSH
    Type: AWS::EC2::KeyPair::KeyName
    Default: vockey
  InstanceType:
    Description: Tamaño instancia EC2
    Type: String
    Default: t2.medium
    AllowedValues:
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    ConstraintDescription: Tipos de instancia validas
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref EC2AMI
      KeyName: !Ref KeyName
      SecurityGroups:
      - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: LandingMBStack
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install -y apache2 dos2unix git nodejs npm
          apache2 -v
          dos2unix --version
          git --version
          nodejs -v
          npm -v
          cd /var/www
          sudo git clone https://github.com/AlbertoMorenoFdez/landing
          echo "<VirtualHost *:80>
            ServerName www.makinonbikes-landing.duckdns.org
            ServerAdmin webmaster@localhost
            DocumentRoot /var/www/landing
            ErrorLog ${APACHE_LOG_DIR}/error.log
            CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>" | sudo tee /etc/apache2/sites-available/landing.conf
          sudo a2ensite landing.conf
          sudo a2dissite 000-default.conf
          sudo systemctl restart apache2
          cd /var/www/landing
          sudo npm install
          sudo npm install --save-dev webpack webpack-cli
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Acesso SSH y web en 8080
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp:
          Ref: SSHLocation
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp:
          Ref: SSHLocation
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp:
          Ref: SSHLocation
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
Outputs:
  InstancePublicIP:
    Description: IP publica de la instancia EC2
    Value: !GetAtt EC2Instance.PublicIp
    Export:
      Name: !Sub "${AWS::StackName}-InstancePublicIP"
  InstancePublicDNS:
    Description: DNS publica de la instancia EC2
    Value: !Sub "http://${EC2Instance.PublicDnsName}"
    Export:
     Name: EC2InstancePublicDNS
